// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3UJUvwC_awWNFQFGdbzTZuhStHG5CQEc',
    appId: '1:145163979194:web:bbf1ed23ccb4b39c683583',
    messagingSenderId: '145163979194',
    projectId: 'breakin-d3da1',
    authDomain: 'breakin-d3da1.firebaseapp.com',
    storageBucket: 'breakin-d3da1.firebasestorage.app',
    measurementId: 'G-8Q8311BJNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHrzgY9xwtgWZhgq_j2j4QAXOmGCwiJgk',
    appId: '1:145163979194:android:74104622cf3c8e2a683583',
    messagingSenderId: '145163979194',
    projectId: 'breakin-d3da1',
    storageBucket: 'breakin-d3da1.firebasestorage.app',
  );

}